<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.2" name="environment" tilewidth="16" tileheight="16" tilecount="720" columns="40">
 <image source="RPG Nature Tileset.png" width="641" height="288"/>
 <tile id="6" type="Node-Coal"/>
 <tile id="7" type="Node-Coal"/>
 <tile id="8" type="Node-Wood"/>
 <tile id="9" type="Node-Wood"/>
 <tile id="30" type="Node-Wall"/>
 <tile id="31" type="Node-Wall"/>
 <tile id="32" type="Node-Wall"/>
 <tile id="33" type="Node-Wall"/>
 <tile id="34" type="Node-Wall"/>
 <tile id="35" type="Node-Wall"/>
 <tile id="36" type="Node-Water"/>
 <tile id="37" type="Node-Water"/>
 <tile id="38" type="Node-Water"/>
 <tile id="39" type="Node-Water"/>
 <tile id="46" type="Node-Coal"/>
 <tile id="47" type="Node-Coal"/>
 <tile id="48" type="Node-Wood"/>
 <tile id="49" type="Node-Wood"/>
 <tile id="70" type="Node-Wall"/>
 <tile id="71" type="Node-Water"/>
 <tile id="72" type="Node-Water"/>
 <tile id="73" type="Node-Water"/>
 <tile id="74" type="Node-Water"/>
 <tile id="75" type="Node-Wall"/>
 <tile id="76" type="Node-Water"/>
 <tile id="77" type="Node-Iron"/>
 <tile id="78" type="Node-Iron"/>
 <tile id="79" type="Node-Water"/>
 <tile id="80" type="Node-Wood"/>
 <tile id="81" type="Node-Wood"/>
 <tile id="84" type="Node-Stone"/>
 <tile id="85" type="Node-Stone"/>
 <tile id="86" type="Node-Coal"/>
 <tile id="87" type="Node-Coal"/>
 <tile id="110" type="Node-Wall"/>
 <tile id="111" type="Node-Water"/>
 <tile id="112" type="Node-Water"/>
 <tile id="113" type="Node-Water"/>
 <tile id="114" type="Node-Water"/>
 <tile id="115" type="Node-Wall"/>
 <tile id="116" type="Node-Water"/>
 <tile id="117" type="Node-Iron"/>
 <tile id="118" type="Node-Iron"/>
 <tile id="119" type="Node-Water"/>
 <tile id="120" type="Node-Wood"/>
 <tile id="121" type="Node-Wood"/>
 <tile id="124" type="Node-Stone"/>
 <tile id="125" type="Node-Stone"/>
 <tile id="126" type="Node-Coal"/>
 <tile id="127" type="Node-Coal"/>
 <tile id="150" type="Node-Wall"/>
 <tile id="151" type="Node-Water"/>
 <tile id="152" type="Node-Water"/>
 <tile id="153" type="Node-Water"/>
 <tile id="154" type="Node-Water"/>
 <tile id="155" type="Node-Wall"/>
 <tile id="156" type="Node-Water"/>
 <tile id="157" type="Node-Water"/>
 <tile id="158" type="Node-Water"/>
 <tile id="159" type="Node-Water"/>
 <tile id="162" type="Node-Water"/>
 <tile id="163" type="Node-Water"/>
 <tile id="166" type="Node-Wall"/>
 <tile id="167" type="Node-Wall"/>
 <tile id="190" type="Node-Wall"/>
 <tile id="191" type="Node-Water"/>
 <tile id="192" type="Node-Water"/>
 <tile id="193" type="Node-Water"/>
 <tile id="194" type="Node-Water"/>
 <tile id="195" type="Node-Wall"/>
 <tile id="196" type="Node-Water"/>
 <tile id="199" type="Node-Water"/>
 <tile id="202" type="Node-Water"/>
 <tile id="203" type="Node-Water"/>
 <tile id="206" type="Node-Wall"/>
 <tile id="207" type="Node-Wall"/>
 <tile id="230" type="Node-Wall"/>
 <tile id="231" type="Node-Wall"/>
 <tile id="232" type="Node-Wall"/>
 <tile id="233" type="Node-Wall"/>
 <tile id="234" type="Node-Wall"/>
 <tile id="235" type="Node-Wall"/>
 <tile id="237" type="Node-Water"/>
 <tile id="238" type="Node-Water"/>
 <tile id="250" type="Node-Water"/>
 <tile id="251" type="Node-Water"/>
 <tile id="252" type="Node-Water"/>
 <tile id="253" type="Node-Water"/>
 <tile id="254" type="Node-Water"/>
 <tile id="255" type="Node-Water"/>
 <tile id="260" type="Node-Water"/>
 <tile id="261" type="Node-Water"/>
 <tile id="262" type="Node-Water"/>
 <tile id="263" type="Node-Water"/>
 <tile id="264" type="Node-Water"/>
 <tile id="265" type="Node-Water"/>
 <tile id="270" type="Node-Wall"/>
 <tile id="271" type="Node-Wall"/>
 <tile id="272" type="Node-Wall"/>
 <tile id="273" type="Node-Wall"/>
 <tile id="274" type="Node-Wall"/>
 <tile id="275" type="Node-Wall"/>
 <tile id="290" type="Node-Water"/>
 <tile id="295" type="Node-Water"/>
 <tile id="297" type="Node-Water"/>
 <tile id="298" type="Node-Water"/>
 <tile id="300" type="Node-Water"/>
 <tile id="305" type="Node-Water"/>
 <tile id="307" type="Node-Water"/>
 <tile id="308" type="Node-Water"/>
 <tile id="310" type="Node-Wall"/>
 <tile id="315" type="Node-Wall"/>
 <tile id="317" type="Node-Iron"/>
 <tile id="318" type="Node-Iron"/>
 <tile id="330" type="Node-Water"/>
 <tile id="335" type="Node-Water"/>
 <tile id="337" type="Node-Water"/>
 <tile id="338" type="Node-Water"/>
 <tile id="340" type="Node-Water"/>
 <tile id="345" type="Node-Water"/>
 <tile id="347" type="Node-Water"/>
 <tile id="348" type="Node-Water"/>
 <tile id="350" type="Node-Wall"/>
 <tile id="355" type="Node-Wall"/>
 <tile id="357" type="Node-Iron"/>
 <tile id="358" type="Node-Iron"/>
 <tile id="370" type="Node-Water"/>
 <tile id="375" type="Node-Water"/>
 <tile id="380" type="Node-Water"/>
 <tile id="385" type="Node-Water"/>
 <tile id="390" type="Node-Wall"/>
 <tile id="395" type="Node-Wall"/>
 <tile id="410" type="Node-Water"/>
 <tile id="415" type="Node-Water"/>
 <tile id="417" type="Node-Water"/>
 <tile id="418" type="Node-Water"/>
 <tile id="420" type="Node-Water"/>
 <tile id="425" type="Node-Water"/>
 <tile id="427" type="Node-Water"/>
 <tile id="428" type="Node-Water"/>
 <tile id="430" type="Node-Wall"/>
 <tile id="435" type="Node-Wall"/>
 <tile id="450" type="Node-Water"/>
 <tile id="451" type="Node-Water"/>
 <tile id="452" type="Node-Water"/>
 <tile id="453" type="Node-Water"/>
 <tile id="454" type="Node-Water"/>
 <tile id="455" type="Node-Water"/>
 <tile id="456" type="Node-Water"/>
 <tile id="459" type="Node-Water"/>
 <tile id="460" type="Node-Water"/>
 <tile id="461" type="Node-Water"/>
 <tile id="462" type="Node-Water"/>
 <tile id="463" type="Node-Water"/>
 <tile id="464" type="Node-Water"/>
 <tile id="465" type="Node-Water"/>
 <tile id="466" type="Node-Water"/>
 <tile id="469" type="Node-Water"/>
 <tile id="470" type="Node-Wall"/>
 <tile id="471" type="Node-Wall"/>
 <tile id="472" type="Node-Wall"/>
 <tile id="473" type="Node-Wall"/>
 <tile id="474" type="Node-Wall"/>
 <tile id="475" type="Node-Wall"/>
 <tile id="506" type="Node-Water"/>
 <tile id="507" type="Node-Water"/>
 <tile id="508" type="Node-Water"/>
 <tile id="509" type="Node-Water"/>
 <tile id="510" type="Node-Wall"/>
 <tile id="511" type="Node-Wall"/>
 <tile id="512" type="Node-Wall"/>
 <tile id="513" type="Node-Wall"/>
 <tile id="514" type="Node-Wall"/>
 <tile id="515" type="Node-Wall"/>
 <tile id="541" type="Node-Water"/>
 <tile id="542" type="Node-Water"/>
 <tile id="543" type="Node-Water"/>
 <tile id="544" type="Node-Water"/>
 <tile id="546" type="Node-Water"/>
 <tile id="549" type="Node-Water"/>
 <tile id="550" type="Node-Wall"/>
 <tile id="555" type="Node-Wall"/>
 <tile id="557" type="Node-Iron"/>
 <tile id="558" type="Node-Iron"/>
 <tile id="581" type="Node-Water"/>
 <tile id="582" type="Node-Water"/>
 <tile id="583" type="Node-Water"/>
 <tile id="584" type="Node-Water"/>
 <tile id="586" type="Node-Water"/>
 <tile id="589" type="Node-Water"/>
 <tile id="590" type="Node-Wall"/>
 <tile id="595" type="Node-Wall"/>
 <tile id="597" type="Node-Iron"/>
 <tile id="598" type="Node-Iron"/>
 <tile id="621" type="Node-Water"/>
 <tile id="622" type="Node-Water"/>
 <tile id="623" type="Node-Water"/>
 <tile id="624" type="Node-Water"/>
 <tile id="626" type="Node-Water"/>
 <tile id="627" type="Node-Water"/>
 <tile id="628" type="Node-Water"/>
 <tile id="629" type="Node-Water"/>
 <tile id="630" type="Node-Wall"/>
 <tile id="635" type="Node-Wall"/>
 <tile id="661" type="Node-Water"/>
 <tile id="662" type="Node-Water"/>
 <tile id="663" type="Node-Water"/>
 <tile id="664" type="Node-Water"/>
 <tile id="666" type="Node-Water"/>
 <tile id="669" type="Node-Water"/>
 <tile id="670" type="Node-Wall"/>
 <tile id="675" type="Node-Wall"/>
 <tile id="707" type="Node-Water"/>
 <tile id="708" type="Node-Water"/>
 <tile id="710" type="Node-Wall"/>
 <tile id="711" type="Node-Wall"/>
 <tile id="712" type="Node-Wall"/>
 <tile id="713" type="Node-Wall"/>
 <tile id="714" type="Node-Wall"/>
 <tile id="715" type="Node-Wall"/>
</tileset>
